//
//  CreatePostProtocols.swift
//  simplesocial
//
//  Created Samet Macit on 13.08.2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol CreatePostWireframeProtocol: AnyObject {

}
// MARK: Presenter -
protocol CreatePostPresenterProtocol: AnyObject {

    var interactor: CreatePostInteractorInputProtocol? { get set }
}

// MARK: Interactor -
protocol CreatePostInteractorOutputProtocol: AnyObject {

    /* Interactor -> Presenter */
}

protocol CreatePostInteractorInputProtocol: AnyObject {

    var presenter: CreatePostInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol CreatePostViewProtocol: AnyObject {

    var presenter: CreatePostPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
