//
//  PostsProtocols.swift
//  simplesocial
//
//  Created Samet Macit on 13.08.2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

// MARK: Wireframe -
protocol PostsWireframeProtocol: AnyObject {
    func routeToCreatePost(delegate: CreatePostDelegate, selectedUser: User)
}
// MARK: Presenter -
protocol PostsPresenterProtocol: AnyObject {

    var interactor: PostsInteractorInputProtocol? { get set }
    
    func viewDidLoad()
    func presentCreateScreen()
    func selectUser(at index: Int)
}

// MARK: Interactor -
protocol PostsInteractorOutputProtocol: AnyObject {

    func presentPosts(posts: [Post])
    func presentUsers(users: [User])
}

protocol PostsInteractorInputProtocol: AnyObject {

    var presenter: PostsInteractorOutputProtocol?  { get set }

    func fetchPosts()
    func fetchUsers()
    
}

// MARK: View -
protocol PostsViewProtocol: AnyObject {

    var presenter: PostsPresenterProtocol?  { get set }
    
    func presentPost(viewModels: [PostViewModel])
    func presentUser(viewModel: UserViewModel)
    func presentUsers(viewModels: [String])
}

struct UserViewModel {
    let userName: String
}
