//
//  PostsInteractor.swift
//  simplesocial
//
//  Created Samet Macit on 13.08.2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PostsInteractor: PostsInteractorInputProtocol {

    weak var presenter: PostsInteractorOutputProtocol?
}
